BEGIN;

INSERT INTO catalog.data_sources (
  source_id,
  name,
  publisher,
  homepage_url,
  documentation_url,
  access_method,
  automation_level,
  coverage_scope,
  spatial_resolution,
  temporal_resolution,
  licence_name,
  attribution_required,
  auth_env_keys,
  enabled,
  source_config,
  notes
)
VALUES
  (
    'wdc_pmksy_public_reports',
    'WDC-PMKSY 2.0 public reports and work exports',
    'Department of Land Resources, Ministry of Rural Development',
    'https://wdcpmksy.dolr.gov.in/reports?roleId=1',
    'https://wdcpmksy.dolr.gov.in/reference/UserManual.pdf',
    'portal_download',
    'assisted',
    'Participating states/UTs; verify every report snapshot',
    'Work/project/admin records; some reports include coordinates and photos',
    'Portal snapshot',
    NULL,
    true,
    '{}',
    false,
    '{"authorisation_required_for_operational_ingestion":true}'::jsonb,
    'Public pages and Excel exports are not a documented stable API. Do not ingest personal data from reports.'
  ),
  (
    'drishti_srishti_authorised_transfer',
    'Drishti/Srishti operational evidence transfer',
    'NRSC/ISRO and authorised WDC-PMKSY programme owners',
    'https://bhuvan.nrsc.gov.in/',
    NULL,
    'restricted_transfer',
    'restricted',
    'Programme coverage after written approval',
    'Work-level geo-tagged observations',
    'Operational',
    NULL,
    true,
    '{}',
    false,
    '{"contains_restricted_media":true,"contains_possible_personal_data":true}'::jsonb,
    'No public production API has been verified. Obtain a data-sharing route and field dictionary from the programme owner.'
  ),
  (
    'soi_abdb',
    'Administrative Boundary Data Base',
    'Survey of India',
    'https://surveyofindia.gov.in/pages/administrative-boundary-data-base-abdb-',
    'https://onlinemaps.surveyofindia.gov.in/User_Manual/User_Guide_online_maps_portal.pdf',
    'portal_download',
    'manual',
    'India; state/UT, district, subdistrict and available village layers',
    '1:1M product',
    'Release snapshot',
    'Survey of India terms for the downloaded product',
    true,
    '{}',
    false,
    '{"preferred_for_official_boundaries":true}'::jsonb,
    'Download from the SoI portal, retain the supplied metadata and licence, and version every boundary release.'
  ),
  (
    'ogd_hydrological_boundaries',
    'Hydrological Boundaries of India',
    'National Water Informatics Centre / data.gov.in',
    'https://www.data.gov.in/catalog/hydrological-boundaries',
    'https://www.data.gov.in/help',
    'direct_download',
    'assisted',
    'India; basin, sub-basin and watershed resources',
    'Polygon boundaries',
    'One-time resource snapshot',
    'Government Open Data License - India',
    true,
    '{DATA_GOV_IN_API_KEY}',
    false,
    '{"catalog_api_available":true}'::jsonb,
    'The catalogue has downloadable ZIP resources. A requested/generated resource API may require a data.gov.in key.'
  ),
  (
    'nwdp_surface_waterbodies',
    'Surface Waterbodies',
    'National Water Data Portal / Space Applications Centre',
    'https://www.nwdp.nwic.gov.in/en/dataset/surface-waterbodies',
    'https://www.nwdp.nwic.gov.in/about/featureswaterdataportal',
    'direct_download',
    'assisted',
    'State/UT resources listed separately; audit completeness before claiming India coverage',
    'Waterbodies larger than 0.1 hectare',
    'Dataset snapshot',
    NULL,
    true,
    '{}',
    false,
    '{"preferred_format":"GeoJSON"}'::jsonb,
    'Resource URLs can be downloaded after enumerating every state/UT and recording missing or duplicate resources.'
  ),
  (
    'cdse_sentinel2_l2a',
    'Sentinel-2 Level-2A',
    'Copernicus Data Space Ecosystem',
    'https://dataspace.copernicus.eu/',
    'https://documentation.dataspace.copernicus.eu/APIs/STAC.html',
    'stac_api',
    'full',
    'India and global',
    '10 m, 20 m and 60 m bands',
    'Satellite acquisition',
    'Copernicus data terms',
    true,
    '{CDSE_CLIENT_ID,CDSE_CLIENT_SECRET}',
    false,
    '{"stac_endpoint":"https://stac.dataspace.copernicus.eu/v1/","collection":"sentinel-2-l2a","statistics_endpoint":"https://sh.dataspace.copernicus.eu/statistics/v1"}'::jsonb,
    'Use surface reflectance, SCL/data masks, valid-pixel thresholds, and polygon statistics. Do not retain full scenes in Postgres.'
  ),
  (
    'cdse_cop_dem_glo30',
    'Copernicus DEM GLO-30',
    'Copernicus Data Space Ecosystem',
    'https://dataspace.copernicus.eu/',
    'https://documentation.dataspace.copernicus.eu/Data/Others/CCM.html',
    'rest_api',
    'full',
    'India and global',
    '30 m DSM',
    'Static product',
    'Copernicus DEM licence',
    true,
    '{CDSE_CLIENT_ID,CDSE_CLIENT_SECRET}',
    false,
    '{"product_type":"COP-DEM_GLO-30-DGED","ccm_registration_required":true}'::jsonb,
    'Automate only after the CDSE account is registered for CCM data.'
  ),
  (
    'imd_gridded_rainfall_025',
    'IMD daily gridded rainfall 0.25 degree',
    'India Meteorological Department',
    'https://www.imdpune.gov.in/cmpg/Griddata/Rainfall_25_NetCDF.html',
    NULL,
    'portal_download',
    'assisted',
    'India grid',
    '0.25 degree',
    'Daily; yearly NetCDF files',
    'IMD dataset terms and citation',
    true,
    '{}',
    false,
    '{"preferred_format":"NetCDF"}'::jsonb,
    'Authoritative historical rainfall context, but the public page is a download interface rather than a documented API.'
  ),
  (
    'nwdp_imd_daily_rainfall',
    'Rainfall Daily IMD',
    'India Meteorological Department / National Water Data Portal',
    'https://www.nwdp.nwic.gov.in/en/dataset/rainfall-daily-imd',
    'https://www.nwdp.nwic.gov.in/about/featureswaterdataportal',
    'direct_download',
    'assisted',
    'District-wise and state-wise India resources',
    'Administrative aggregates/stations as supplied',
    'Daily',
    NULL,
    true,
    '{}',
    false,
    '{"formats":["CSV"]}'::jsonb,
    'Use for official administrative rainfall context. Record resource update timestamps and do not assume a stable undocumented URL.'
  ),
  (
    'imd_state_rainfall_api',
    'IMD state/subdivision rainfall API',
    'India Meteorological Department',
    'https://mausam.imd.gov.in/',
    'https://mausam.imd.gov.in/imd_latest/contents/api.pdf',
    'rest_api',
    'full',
    'India; state/subdivision aggregates',
    'State or meteorological subdivision',
    'Daily/forecast depending on endpoint',
    NULL,
    true,
    '{}',
    false,
    '{}'::jsonb,
    'Useful for dashboard context, not for evaluating an individual work or micro-watershed.'
  ),
  (
    'nasa_gpm_imerg_v07',
    'GPM IMERG Version 07',
    'NASA GES DISC',
    'https://gpm.nasa.gov/data/imerg',
    'https://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGHH.07/',
    'rest_api',
    'full',
    'India and global',
    '0.1 degree',
    'Half-hourly and aggregated products',
    'NASA Earthdata terms',
    true,
    '{NASA_EARTHDATA_TOKEN}',
    false,
    '{"protocol":"OPeNDAP","product_version":"07"}'::jsonb,
    'Use as an automated corroborating/fallback rainfall source; retain IMD as the preferred Indian authority when suitable data is available.'
  ),
  (
    'soilgrids_wcs',
    'SoilGrids',
    'ISRIC - World Soil Information',
    'https://soilgrids.org/',
    'https://docs.isric.org/globaldata/soilgrids/wcs.html',
    'ogc_service',
    'full',
    'India and global',
    '250 m',
    'Static/versioned product',
    'CC BY 4.0',
    true,
    '{}',
    false,
    '{"protocol":"WCS","avoid_unstable_rest_api":true}'::jsonb,
    'Use WCS for bounded subsets and store property, depth, statistic, version, uncertainty, and attribution.'
  ),
  (
    'bhuvan_thematic_wms',
    'Bhuvan thematic WMS/WMTS',
    'NRSC/ISRO',
    'https://bhuvan.nrsc.gov.in/',
    'https://bhuvan.nrsc.gov.in/wiki/index.php/How_to_use_WMS_services',
    'ogc_service',
    'assisted',
    'Layer-dependent; many layers are state/year specific',
    'Layer-dependent',
    'Layer-dependent',
    'Bhuvan terms for each layer',
    true,
    '{}',
    false,
    '{"wms_endpoint":"https://bhuvan-vec2.nrsc.gov.in/bhuvan/wms","visualisation_only_by_default":true}'::jsonb,
    'Automate map display and capabilities checks. Do not treat rendered WMS pixels as a bulk analytical dataset without explicit rights and metadata.'
  ),
  (
    'bhuvan_thematic_download',
    'Bhuvan thematic Get Data / Clip and Ship',
    'NRSC/ISRO',
    'https://bhuvan-app1.nrsc.gov.in/thematic',
    'https://bhuvan.nrsc.gov.in/wiki/index.php/List_of_Vector_%28Thematic_Maps%29_datasets',
    'portal_download',
    'manual',
    'Layer and release dependent; never assume Pan-India completeness',
    'Layer-dependent',
    'Release snapshot',
    'Bhuvan terms or MoU for the requested dataset',
    true,
    '{}',
    false,
    '{"may_require_account":true,"may_require_mou":true}'::jsonb,
    'The user must request/download permitted LULC or thematic files. The importer can be automated after files and terms are supplied.'
  )
ON CONFLICT (source_id) DO UPDATE SET
  name = EXCLUDED.name,
  publisher = EXCLUDED.publisher,
  homepage_url = EXCLUDED.homepage_url,
  documentation_url = EXCLUDED.documentation_url,
  access_method = EXCLUDED.access_method,
  automation_level = EXCLUDED.automation_level,
  coverage_scope = EXCLUDED.coverage_scope,
  spatial_resolution = EXCLUDED.spatial_resolution,
  temporal_resolution = EXCLUDED.temporal_resolution,
  licence_name = EXCLUDED.licence_name,
  attribution_required = EXCLUDED.attribution_required,
  auth_env_keys = EXCLUDED.auth_env_keys,
  source_config = EXCLUDED.source_config,
  notes = EXCLUDED.notes;

COMMIT;
